name = input ("what is your name")
age = int(input ("enter your age"))
height = float(input("what is your height"))
shoesize = int(input("what is your shoesize"))
location = input("where do you stay")
print (" Hello, My name is",name)
print ("i am", age, "years old" )
print ("My shoesize is", shoesize)
print ("i am", height, "meters tall")